#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test WarehouseManagement
            image: mcr.microsoft.com/dotnet/sdk:5.0
            caches:
              - dotnetcore
            script:
              - export WM=WarehouseManagement
              - dotnet restore ./WarehouseManagement
              - dotnet build $WM
              - dotnet test $WM
        - step:
            name: Build and Test Logistics
            image: node:16
            caches:
              - node
            script:
              - cd ./Logistics
              - npm install
              - npm test

    - step:
        name: Logistics Deployment to execute on Virtual Machine
        deployment: Production
        script: 
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: 'root'
              SERVER: 'vsgate-ssh.dei.isep.ipp.pt'
              REMOTE_PATH: '/logisticsAPI'
              LOCAL_PATH: './Logistics'
              SSH_KEY: $MYKEY
              EXTRA_ARGS: ["-P","10982 "]
